USE ZION
GO

--QUERY TO GET THE TOTAL SCORE FOR EACH STUDENT

WITH CUMULATIVE(ADM_NO, Student_Name, TOTAL) AS
(SELECT ADM_NO, Student_Name, (Maths + English + BasicScience + BST + YORUBA + PVS + CCA + IT + CRS) AS TOTAL
FROM AcademicResults)
--QUERY TO DISPLAY POSITION OF EACH STUDENTS USING THE RANK() OVER FUNCTION 
SELECT ADM_NO, Student_Name, TOTAL, RANK()OVER(ORDER BY TOTAL DESC) AS POSITION
FROM CUMULATIVE
ORDER BY POSITION OFFSET 1 ROWS FETCH NEXT 3 ROWS ONLY  -- QUERY TO GET 1ST RUNNER-UP AND 2ND RUNNER-UP
GO 


